#!/usr/bin/env bash

#lein with-profiles +native-image "do" clean, uberjar

export JAVA_HOME=$GRAALVM_HOME
export PATH=$GRAALVM_HOME/bin:$PATH

gu install native-image

args=( "-jar" "target/tetris-0.1.0-SNAPSHOT-standalone.jar"
       "-H:Name=tetris"
       "-H:+ReportExceptionStackTraces"
       "-J-Dclojure.spec.skip-macros=true"
       "-J-Dclojure.compiler.direct-linking=true"
       "--initialize-at-run-time=java.lang.Math\$RandomNumberGeneratorHolder,sun.awt.dnd.SunDropTargetContextPeer\$EventDispatcher"
       "--initialize-at-build-time"
       "-H:Log=registerResource:"
       "-H:EnableURLProtocols=http,https,jar"
       "--enable-all-security-services"
       "-H:+JNI"
       "--verbose"
       "--no-fallback"
       "--no-server"
       "--report-unsupported-elements-at-runtime")

"$GRAALVM_HOME/bin/native-image" "${args[@]}"
